name: build

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-9 libclang-9-dev llvm-9-dev
    - name: Build
      run: make CC=clang-9 LLVM_CFLAGS="`llvm-config-9 --cflags`" LLVM_LDFLAGS="`llvm-config-9 --ldflags`"
    - name: Test
      run: make test
  windows:
    runs-on: windows-latest
    env:
      VCVARSALL: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"'
      VCARCH: 'x64'
    steps:
    - uses: actions/checkout@v1
    - name: Install LLVM
      shell: cmd
      run: |
        curl -o llvm.zip "https://f002.backblazeb2.com/file/felipeagc-llvm/llvm.zip"
        7z x -y llvm.zip
    - name: Build
      shell: cmd
      run: |
        call %VCVARSALL% %VCARCH%
        nmake LLVM_PATH=.\llvm
    - name: Test
      shell: cmd
      run: |
        call %VCVARSALL% %VCARCH%
        nmake test
