name: build

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-9 libclang-9-dev llvm-9-dev
    - name: Build
      run: make CC=clang-9 LLVM_CFLAGS="`llvm-config-9 --cflags`" LLVM_LDFLAGS="`llvm-config-9 --ldflags`"
    - name: Test
      run: make test
